# Generated by Django 5.2.5 on 2025-08-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='tbl_user_de_rank_a50b61_idx',
            old_name='user_profil_rank_eca27f_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='tbl_user_de_unitnam_fc46f8_idx',
            old_name='user_profil_unitnam_60f3e7_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='tbl_user_de_status_56b24d_idx',
            old_name='user_profil_status_6d69fb_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='tbl_user_de_created_7ac053_idx',
            old_name='user_profil_created_26443b_idx',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='tbl_user_details',
        ),
    ]
