# Generated by Django 5.2.5 on 2025-08-18 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_profil_rank_eca27f_idx_tbl_user_de_rank_a50b61_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=90)),
                ('remarks', models.CharField(blank=True, max_length=900, null=True)),
                ('insert_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_datetime', models.DateTimeField(blank=True)),
                ('username', models.CharField(max_length=50)),
                ('is_active', models.IntegerField(default=1)),
                ('personal_no', models.CharField(blank=True, max_length=50, null=True)),
                ('question1', models.CharField(blank=True, max_length=10, null=True)),
                ('question2', models.CharField(blank=True, max_length=10, null=True)),
                ('question3', models.CharField(blank=True, max_length=10, null=True)),
                ('question4', models.CharField(blank=True, max_length=10, null=True)),
                ('avg_feedback', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'tbl_usermgmt_feedback',
            },
        ),
        migrations.CreateModel(
            name='HomePageInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_type', models.CharField(choices=[('instructions', 'Instructions'), ('offline', 'Offline'), ('downloads', 'Downloads'), ('publications', 'Publications')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'information_home_page',
            },
        ),
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tbl_role_master',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=150)),
                ('userlogin', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=510)),
                ('confirm_password', models.CharField(max_length=510)),
                ('personal_no', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('ship_name', models.CharField(max_length=100)),
                ('employee_type', models.CharField(max_length=50)),
                ('establishment', models.CharField(max_length=100)),
                ('nudemail', models.EmailField(max_length=150)),
                ('phone_no', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=20)),
                ('sso_user', models.BooleanField(default=False)),
                ('h', models.BooleanField(default=False)),
                ('l', models.BooleanField(default=False)),
                ('e', models.BooleanField(default=False)),
                ('x', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tbl_user_details',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
