# Generated by Django 5.2.5 on 2025-08-18 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_feedback_homepageinformation_rolemaster_userdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='e',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='h',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='l',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='x',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='sso_user',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator(message='Must be 0 or 1', regex='^[01]$')]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='status',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator(message='Must be 0 or 1', regex='^[01]$')]),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='E',
            field=models.CharField(default=0, max_length=1, validators=[django.core.validators.RegexValidator(message='Must be 0 or 1', regex='^[01]$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='H',
            field=models.CharField(default=0, max_length=1, validators=[django.core.validators.RegexValidator(message='Must be 0 or 1', regex='^[01]$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='L',
            field=models.CharField(default=0, max_length=1, validators=[django.core.validators.RegexValidator(message='Must be 0 or 1', regex='^[01]$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='X',
            field=models.CharField(default=0, max_length=1, validators=[django.core.validators.RegexValidator(message='Must be 0 or 1', regex='^[01]$')]),
            preserve_default=False,
        ),
    ]
