# Generated by Django 5.2.5 on 2025-08-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userdetails_e_remove_userdetails_h_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='homepageinformation',
            name='content',
        ),
        migrations.RemoveField(
            model_name='homepageinformation',
            name='tab_type',
        ),
        migrations.RemoveField(
            model_name='homepageinformation',
            name='title',
        ),
        migrations.AddField(
            model_name='homepageinformation',
            name='header_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepageinformation',
            name='header_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepageinformation',
            name='level_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepageinformation',
            name='level_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepageinformation',
            name='section_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepageinformation',
            name='section_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='designation_email',
            field=models.EmailField(default='test@navy.mil', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='E',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='H',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='L',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='X',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='sso_user',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='status',
            field=models.CharField(default='2', max_length=1),
        ),
        migrations.AlterModelTable(
            name='homepageinformation',
            table='tbl_cmms_headers_details',
        ),
    ]
